spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?allowMultiQueries=true&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    password: zhx199503
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  profiles:
    active:
      - dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
logging:
  level:
    root: info
    "[com.tears.vscodedemo]": debug
# mybatis:
#   mapper-locations: classpath*:mappers/*.xml
#   config-location: classpath:mybatis-config.xml
#   type-aliases-package: com.tears.vscodedemo
# configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
